/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shopping` | `/shopping`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/birthdays` | `/birthdays`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/birthdays/new` | `/birthdays/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits` | `/habits`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits/new` | `/habits/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notes` | `/notes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notes/new` | `/notes/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/birthdays/[id]` | `/birthdays/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/habits/[id]` | `/habits/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/notes/[id]` | `/notes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/shopping` | `/shopping`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/birthdays` | `/birthdays`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/birthdays/new` | `/birthdays/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/habits` | `/habits`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/habits/new` | `/habits/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notes` | `/notes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notes/new` | `/notes/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/birthdays/[id]` | `/birthdays/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}/habits/[id]` | `/habits/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}/notes/[id]` | `/notes/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/shopping${`?${string}` | `#${string}` | ''}` | `/shopping${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/birthdays${`?${string}` | `#${string}` | ''}` | `/birthdays${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/birthdays/new${`?${string}` | `#${string}` | ''}` | `/birthdays/new${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/habits${`?${string}` | `#${string}` | ''}` | `/habits${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/habits/new${`?${string}` | `#${string}` | ''}` | `/habits/new${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notes${`?${string}` | `#${string}` | ''}` | `/notes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notes/new${`?${string}` | `#${string}` | ''}` | `/notes/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shopping` | `/shopping`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/birthdays` | `/birthdays`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/birthdays/new` | `/birthdays/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits` | `/habits`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits/new` | `/habits/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notes` | `/notes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notes/new` | `/notes/new`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/birthdays/${Router.SingleRoutePart<T>}` | `/birthdays/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/habits/${Router.SingleRoutePart<T>}` | `/habits/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/notes/${Router.SingleRoutePart<T>}` | `/notes/${Router.SingleRoutePart<T>}` | { pathname: `${'/(tabs)'}/birthdays/[id]` | `/birthdays/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/habits/[id]` | `/habits/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/notes/[id]` | `/notes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
